title: He(Francois) Hao
description: PhD Researcher in smart battery system

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark

header_pages:
  - index.md
  - projects.md
  - publications.md
  - contact.md
